name: lstrv_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  carousel_slider: ^1.3.0
  flutter_spinkit: ^4.1.2
  palette_generator: ^0.2.3
  provider: ^3.2.0
  firebase_auth: ^0.18.0+1
  cloud_firestore:
  flutter_facebook_login: ^3.0.0

  firebase_core : ^0.5.0
  flare_flutter: ^2.0.6
  google_fonts: ^1.0.0
  flutter_datetime_picker:
  shared_preferences: ^0.5.10
  #fluttertoast: ^7.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_sign_in: ^4.5.4
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.2.0
  dio: ^1.0.13
  fluttertoast: ^3.1.3
  cached_network_image: ^2.3.2+1
  flutter_rating_bar: ^3.0.1+1
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0
dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/img/incredible.jpg"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/img/
    - assets/images/attract/
    - assets/images/Patna/
    - assets/images/gaya/
    - assets/images/nalanda/
    - assets/images/pawapuri/
    - assets/images/rajgir/
    - assets/images/vaishali/
    - assets/images/icons/
    - assets/images/image/
    - assets/images/hotels/
    - assets/eventimages/
    - assets/images/curve.flr

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/font/cm_sans_serif_2012.ttf
    - family: BJ Regular
      fonts:
        - asset: assets/font/bahij-janna-regular.ttf
    - family: BJ Bold
      fonts:
        - asset: assets/font/bahij-janna-bold.ttf
    - family: Oxygen
      fonts:
        - asset: assets/font/Oxygen-Regular.ttf
        - asset: assets/font/Oxygen-Light.ttf
        - asset: assets/font/Oxygen-Bold.ttf